version: '2.1'

services:

    pg82:
      ports:
        - "54312:5432"
      image: datagrip/postgres:8.2
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg84:
      ports:
        - "54314:5432"
      image: postgres:8.4
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg90:
      ports:
        - "54320:5432"
      image: postgres:9.0
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg91:
      ports:
        - "54321:5432"
      image: postgres:9.1
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg92:
      ports:
        - "54322:5432"
      image: postgres:9.2-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg93:
      ports:
        - "54323:5432"
      image: postgres:9.3-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg94:
      ports:
        - "54324:5432"
      image: postgres:9.4-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg95:
      ports:
        - "54325:5432"
      image: postgres:9.5-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg96:
      ports:
        - "54326:5432"
      image: postgres:9.6-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg100:
      ports:
        - "54330:5432"
      image: postgres:10.3-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"

    pg10X:
      ports:
        - "54331:5432"
      image: postgres:10-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"

    greenplum:
      ports:
        - "54302:5432"
      image: datagrip/greenplum
      healthcheck:
        test: grep -r -i --include \*.log "Database successfully started" || exit 1
        interval: 20s
        timeout: 10s
        retries: 5

    mysql51:
      ports:
        - "33051:3306"
      image: datagrip/mysql:5.1
      env_file: .env
      healthcheck:
        test: "exit 0"

    mysql55:
      privileged: true
      ports:
        - "33055:3306"
      image: mysql:5.5
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    mysql56:
      ports:
        - "33056:3306"
      image: mysql:5.6
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    mysql57:
      ports:
        - "33057:3306"
      image: mysql:5.7
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    mysql803:
      image: mysql:8.0.3
      ports:
        - "33080:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci, --log-bin-trust-function-creators=true, --default_authentication_plugin=mysql_native_password]
      healthcheck:
        test: "exit 0"

    mysql80X:
      image: mysql:8
      ports:
        - "33081:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci, --log-bin-trust-function-creators=true, --default_authentication_plugin=mysql_native_password]
      healthcheck:
        test: "exit 0"

    memsql:
      image: datagrip/memsql
      ports:
        - "33088:3306"
      environment:
        - IGNORE_MIN_REQUIREMENTS=1
      healthcheck:
        test: "exit 0"

    # for possible compatibility
    maria10:
      ports:
        - "33040:3306"
      image: mariadb:10.0
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria55:
      image: mariadb:5.5
      ports:
        - "33045:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria52:
      image: datagrip/mariadb:5.2
      ports:
        - "33042:3306"
      env_file: .env
      healthcheck:
        test: "exit 0"

    maria53:
      image: datagrip/mariadb:5.3
      ports:
        - "33043:3306"
      env_file: .env
      healthcheck:
        test: "exit 0"

    maria100:
      image: mariadb:10.0
      ports:
        - "33100:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria101:
      image: mariadb:10.1
      ports:
        - "33101:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria102:
      image: mariadb:10.2
      ports:
        - "33102:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria103:
      image: mariadb:10.3
      ports:
        - "33103:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria1027:
      image: mariadb:10.2.7
      ports:
        - "33127:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria1024:
      image: datagrip/mariadb:10.2.4
      ports:
        - "33124:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria1025:
      image: mariadb:10.2.5
      ports:
        - "33125:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    # oracle VM options
    # -Duser.country=en -Duser.language=en
    # todo: use debian:wheezy
    oracle11:
      ports:
        - "1521:1521"
      image: datagrip/oracle:11.2
      env_file: .env
      healthcheck:
        test: "exit 0"
    
    # oracle 11.2.0.2 express edition (official)
    oracle112:
      ports:
        - "15112:1521"
      image: datagrip/oracle:11.2.0.2-xe
      shm_size: 1g
      env_file: .env
    
    # oracle 12.1.0.2 standart edition 2 (official)
    # WARN: 12GB; start takes about 5 min
    oracle121:
      ports:
        - "15121:1521"
      image: datagrip/oracle:12.1.0.2-se2
      env_file: .env
      healthcheck:
        test: grep "Database creation complete" /opt/oracle/cfgtoollogs/dbca/XE/XE.log || exit 1
        interval: 5m
        timeout: 10s
        retries: 10

    db2:
      privileged: true
      image: datagrip/db2
      ports:
        - "50000:50000"
      env_file: .env
      healthcheck:
        test: "exit 0"

    hsqldb200:
      image: datagrip/hsqldb:2.0.0
      ports:
        - "9001:9001"
      env_file: .env
      healthcheck:
        test: "exit 0"

    hsqldb233:
        image: datagrip/hsqldb:2.3.3
        ports:
        - "9002:9001"
        env_file: .env
        healthcheck:
          test: "exit 0"

    derby1011:
      image: datagrip/derby-server:10.11
      ports:
        - "1527:1527"
      env_file: .env
      healthcheck:
        test: "exit 0"

    derby1012:
      image: datagrip/derby-server:10.12
      ports:
        - "1528:1527"
      env_file: .env
      healthcheck:
        test: "exit 0"

    h2:
      image: datagrip/h2:1.3
      ports:
        - "9092:9092"
      env_file: .env
      healthcheck:
        test: "exit 0"

    # needs about 30 seconds for proper start and initialization
    sybase157:
      image: datagrip/sybase:15.7
      ports:
        - "5000:5000"
      env_file: .env
      hostname: dksybase
      healthcheck:
        test: "exit 0"

    sybase160:
      privileged: true
      image: datagrip/sybase:16.0
      ports:
        - "5001:5000"
      env_file: .env
      hostname: mysybase
      healthcheck:
        test: "exit 0"

    mssqllinux:
      privileged: true
      image: datagrip/mssql-server-linux
      ports:
        - "1433:1433"
      env_file: .env
      healthcheck:
        test: grep "Starting up database '${MSSQL_DB}'." /var/opt/mssql/log/errorlog || exit 1
        interval: 3m
        timeout: 10s
        retries: 5

    # IBM Informix Innovator-C
    informix:
      privileged: true
      image: ibmcom/informix-innovator-c:latest
      ports:
        - "9088:9088"
        - "27017:27017"
        - "27018:27018"
      env_file: .env
      healthcheck:
        test: "exit 0"

    vertica72:
      image: datagrip/vertica:7.2
      ports:
        - "5433:5433"
      env_file: .env
      healthcheck:
        test: grep "Create DB complete, signaling OK" /opt/vertica/log/adminTools.log || exit 1
        interval: 3m
        timeout: 10s
        retries: 5

    exasol:
      privileged: true
      image: datagrip/exasol:latest
      ports:
        - "8899:8888"
      env_file: .env
      healthcheck:
        test: grep -r 'CREATE SCHEMA' /exa/logs/db/DB1/ || exit 1
        interval: 3m
        timeout: 10s
        retries: 5

    # Intersystems Caché-DB
    # db: SAMPLES
    # user: _SYSTEM
    # pwd: SYS
    # jdbc:Cache://<host>:1972/SAMPLES
    intersystemscache:
      image: pscherrer80/cachedb
      ports:
        - "57772:57772"
        - "1972:1972"
      env_file: .env
      healthcheck:
        test: "exit 0"

    mongo32:
      image: tutum/mongodb:3.2
      ports:
        - "27117:27017"
        - "28017:28017"
      env_file: .env
      healthcheck:
        test: "exit 0"
