version: '2'
#for test environment. requires min 4Gb RAM
services:    
    pg96:
      ports:
        - "54326:5432"
      image: postgres:9.6-alpine
      env_file: .env

    mysql57:
      ports:
        - "33057:3306"
      image: mysql:5.7
      env_file: .env
      command: [mysqld, --character-set-server=utf8]
    
    oracle11:
      ports:
        - "1521:1521"
      image: datagrip/oracle:11.2
      env_file: .env

    db2:
      privileged: true
      image: datagrip/db2
      ports:
        - "50000:50000"
      env_file: .env

    hsqldb233:
        image: datagrip/hsqldb:2.3.3
        ports:
        - "9002:9001"
        env_file: .env

    derby1012:
      image: datagrip/derby-server:10.12
      ports:
        - "1528:1527"
      env_file: .env

    h2:
      image: datagrip/h2:1.3
      ports:
        - "9092:9092"
      env_file: .env

    # needs about 30 seconds for proper start and initialization
    sybase157:
      image: datagrip/sybase:15.7
      ports:
        - "5000:5000"
      env_file: .env
      hostname: dksybase

    mssqllinux:
      privileged: true
      image: datagrip/mssql-server-linux
      ports:
        - "1433:1433"
      env_file: .env

